// <auto-generated />
using System;
using Lame.Backend.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lame.Backend.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301112051_TranslationContentIdRename")]
    partial class TranslationContentIdRename
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AssetEntityAssetEntity", b =>
                {
                    b.Property<Guid>("AssetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LinkedContentId")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetEntityId", "LinkedContentId");

                    b.HasIndex("LinkedContentId");

                    b.ToTable("AssetLinks", (string)null);
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.TranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinorVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("AssetEntityAssetEntity", b =>
                {
                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", null)
                        .WithMany()
                        .HasForeignKey("AssetEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", null)
                        .WithMany()
                        .HasForeignKey("LinkedContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.TranslationEntity", b =>
                {
                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", "Asset")
                        .WithMany("Translations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.AssetEntity", b =>
                {
                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
