// <auto-generated />
using System;
using Lame.Backend.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lame.Backend.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260325093243_ChangeLog")]
    partial class ChangeLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AssetEntityTagEntity", b =>
                {
                    b.Property<Guid>("AssetsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("AssetTags", (string)null);
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.AssetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AssetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextNotes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.AssetLinkEntity", b =>
                {
                    b.Property<Guid>("AssetEntityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LinkedContentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Synced")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssetEntityId", "LinkedContentId");

                    b.HasIndex("LinkedContentId");

                    b.ToTable("AssetLinks", (string)null);
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.ChangeLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceAction")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ChangeLogEntries");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.LanguageEntity", b =>
                {
                    b.Property<string>("LanguageCode")
                        .HasColumnType("TEXT");

                    b.HasKey("LanguageCode");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.TagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.TargetAssetTranslationEntity", b =>
                {
                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranslationId")
                        .HasColumnType("TEXT");

                    b.HasKey("AssetId", "Language");

                    b.HasIndex("TranslationId");

                    b.ToTable("TargetAssetTranslations");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.TranslationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinorVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("TagEntityTranslationEntity", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TranslationsId")
                        .HasColumnType("TEXT");

                    b.HasKey("TagsId", "TranslationsId");

                    b.HasIndex("TranslationsId");

                    b.ToTable("TranslationTags", (string)null);
                });

            modelBuilder.Entity("AssetEntityTagEntity", b =>
                {
                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", null)
                        .WithMany()
                        .HasForeignKey("AssetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lame.Backend.EntityFramework.Models.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.AssetLinkEntity", b =>
                {
                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", "AssetEntity")
                        .WithMany("LinkedTo")
                        .HasForeignKey("AssetEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", "LinkedAssetEntity")
                        .WithMany("LinkedFrom")
                        .HasForeignKey("LinkedContentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetEntity");

                    b.Navigation("LinkedAssetEntity");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.TargetAssetTranslationEntity", b =>
                {
                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", "Asset")
                        .WithMany("TargetedTranslations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lame.Backend.EntityFramework.Models.TranslationEntity", "Translation")
                        .WithMany()
                        .HasForeignKey("TranslationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Translation");
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.TranslationEntity", b =>
                {
                    b.HasOne("Lame.Backend.EntityFramework.Models.AssetEntity", "Asset")
                        .WithMany("Translations")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("TagEntityTranslationEntity", b =>
                {
                    b.HasOne("Lame.Backend.EntityFramework.Models.TagEntity", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lame.Backend.EntityFramework.Models.TranslationEntity", null)
                        .WithMany()
                        .HasForeignKey("TranslationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lame.Backend.EntityFramework.Models.AssetEntity", b =>
                {
                    b.Navigation("LinkedFrom");

                    b.Navigation("LinkedTo");

                    b.Navigation("TargetedTranslations");

                    b.Navigation("Translations");
                });
#pragma warning restore 612, 618
        }
    }
}
