name: "Lame Deployment"

on:
  push:
    tags:
      - 'v*'
    
env:
    PROJECT_NAME: "Lame.Frontend/Lame.Frontend.csproj"
    VERSION: ${{ github.ref_name }}
    
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          
      - name: Restore dependencies
        run: dotnet restore 
        
      - name: Set version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        
      - name: Build
        run: dotnet build ${{ env.PROJECT_NAME }} \ 
        -c Release \ 
        --no-restore \
        -p:Version=${{ env.VERSION }}

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_NAME }} \
        -c Release \
        --self-contained \
        --no-build \
        -r win-x64 \
        -o ./publish \
        -p:PublishSingleFile=true

      - name: Zip output
        run: Compress-Archive -Path publish/* -DestinationPath lame-${{ github.ref_name }}-win-x64.zip
 
# Skip whilst testing    
#      - name: Create Release
#        uses: softprops/action-gh-release
#        with:
#          files: lame-${{ github.ref_name }}-win-x64.zip
#          prerelease: ${{ contains(github.ref, 'beta') }}
#        env:
#            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            