name: "Lame Release"

on:
  push:
    branches:
      - main
      - develop
    
env:
    PROJECT_NAME: "Lame.Frontend/Lame.Frontend.csproj"
    
jobs:
  version:
    runs-on: windows-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      preReleaseTag: ${{ steps.gitversion.outputs.preReleaseTag }}
      informationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}
      assemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}
      assemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # REQUIRED for GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        
  build:
    needs: version
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_NAME }} -r win-x64

      - name: Build
        run: >
          dotnet build ${{ env.PROJECT_NAME }} 
          -c Release 
          --no-restore 
          -p:Version=${{ needs.version.outputs.semVer }} 
          -p:AssemblyVersion=${{ needs.version.outputs.assemblySemVer }} 
          -p:FileVersion=${{ needs.version.outputs.assemblySemFileVer }} 
          -p:InformationalVersion=${{ needs.version.outputs.informationalVersion }}

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_NAME }} -c Release --self-contained --no-build -r win-x64 -o ./publish -p:PublishSingleFile=true
        
      - name: Zip output
        run: Compress-Archive -Path publish/* -DestinationPath lame-${{ needs.version.outputs.semVer }}-win-x64.zip
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: lame-${{ needs.version.outputs.semVer }}-win-x64.zip
      
  release:
    needs: 
      - version
      - build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
        
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: lame-${{ needs.version.outputs.semVer }}-win-x64.zip
          tag_name: v${{ needs.version.outputs.semVer }}
          name: v${{ needs.version.outputs.semVer }}
          prerelease: ${{ github.ref == 'refs/heads/develop' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            